# Generated by Django 5.1.7 on 2025-06-15 23:52

import myapp.models
import myapp.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userImage',
            field=models.ImageField(blank=True, null=True, storage=myapp.storages.OverwriteStorage(), upload_to=myapp.models.keep_filename),
        ),
    ]
