# Generated by Django 5.1.7 on 2025-06-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chatmessage_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
    ]
